//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.21 at 02:11:26 PM EDT 
//

package com.gtnexus.pmm.app.platform.module.model.design;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}transactionType"/>
 *         &lt;element ref="{}isCollection"/>
 *         &lt;element ref="{}anchorOQL"/>
 *         &lt;element ref="{}requiredDocStates"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "transactionType", "isCollection", "anchorOQL", "requiredDocStates" })
@XmlRootElement(name = "anchor")
public class Anchor {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String transactionType;
    protected boolean isCollection;
    @XmlElement(required = true)
    protected String anchorOQL;
    @XmlElement(required = true)
    protected String requiredDocStates;

    /**
     * Gets the value of the transactionType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTransactionType() {
	return transactionType;
    }

    /**
     * Sets the value of the transactionType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTransactionType(String value) {
	this.transactionType = value;
    }

    /**
     * Gets the value of the isCollection property.
     * 
     */
    public boolean isIsCollection() {
	return isCollection;
    }

    /**
     * Sets the value of the isCollection property.
     * 
     */
    public void setIsCollection(boolean value) {
	this.isCollection = value;
    }

    /**
     * Gets the value of the anchorOQL property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAnchorOQL() {
	return anchorOQL;
    }

    /**
     * Sets the value of the anchorOQL property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAnchorOQL(String value) {
	this.anchorOQL = value;
    }

    /**
     * Gets the value of the requiredDocStates property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRequiredDocStates() {
	return requiredDocStates;
    }

    /**
     * Sets the value of the requiredDocStates property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRequiredDocStates(String value) {
	this.requiredDocStates = value;
    }

}
