//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.26 at 06:23:51 PM PDT 
//

package com.gtnexus.pmm.app.platform.module.model.typeextension;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}__metadata"/>
 *         &lt;element ref="{}type"/>
 *         &lt;element ref="{}uid"/>
 *         &lt;element ref="{}platformModuleId"/>
 *         &lt;element ref="{}platformModuleType"/>
 *         &lt;element ref="{}documentType"/>
 *         &lt;element ref="{}apiVersion"/>
 *         &lt;element ref="{}status"/>
 *         &lt;element ref="{}rank"/>
 *         &lt;element ref="{}callbacks"/>
 *         &lt;element ref="{}fingerprint"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "metadata", "type", "uid", "platformModuleId", "platformModuleType", "documentType",
	"apiVersion", "status", "rank", "callbacks", "fingerprint" })
@XmlRootElement(name = "TYPEEXTENSIOND1")
public class TypeExtensionD1 {

    @XmlElement(name = "__metadata", required = true)
    protected Metadata metadata;
    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    protected BigInteger uid;
    @XmlElement(required = true)
    protected BigInteger platformModuleId;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String platformModuleType;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String documentType;
    @XmlElement(required = true)
    protected BigInteger apiVersion;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String status;
    @XmlElement(required = true)
    protected BigInteger rank;
    @XmlElement(required = true)
    protected Callbacks callbacks;
    @XmlElement(required = true)
    protected String fingerprint;

    /**
     * Gets the value of the metadata property.
     * 
     * @return possible object is {@link Metadata }
     * 
     */
    public Metadata getMetadata() {
	return metadata;
    }

    /**
     * Sets the value of the metadata property.
     * 
     * @param value
     *            allowed object is {@link Metadata }
     * 
     */
    public void setMetadata(Metadata value) {
	this.metadata = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getType() {
	return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setType(String value) {
	this.type = value;
    }

    /**
     * Gets the value of the uid property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getUid() {
	return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setUid(BigInteger value) {
	this.uid = value;
    }

    /**
     * Gets the value of the platformModuleId property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getPlatformModuleId() {
	return platformModuleId;
    }

    /**
     * Sets the value of the platformModuleId property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setPlatformModuleId(BigInteger value) {
	this.platformModuleId = value;
    }

    /**
     * Gets the value of the platformModuleType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPlatformModuleType() {
	return platformModuleType;
    }

    /**
     * Sets the value of the platformModuleType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPlatformModuleType(String value) {
	this.platformModuleType = value;
    }

    /**
     * Gets the value of the documentType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDocumentType() {
	return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDocumentType(String value) {
	this.documentType = value;
    }

    /**
     * Gets the value of the apiVersion property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getApiVersion() {
	return apiVersion;
    }

    /**
     * Sets the value of the apiVersion property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setApiVersion(BigInteger value) {
	this.apiVersion = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStatus() {
	return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setStatus(String value) {
	this.status = value;
    }

    /**
     * Gets the value of the rank property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getRank() {
	return rank;
    }

    /**
     * Sets the value of the rank property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setRank(BigInteger value) {
	this.rank = value;
    }

    /**
     * Gets the value of the callbacks property.
     * 
     * @return possible object is {@link Callbacks }
     * 
     */
    public Callbacks getCallbacks() {
	return callbacks;
    }

    /**
     * Sets the value of the callbacks property.
     * 
     * @param value
     *            allowed object is {@link Callbacks }
     * 
     */
    public void setCallbacks(Callbacks value) {
	this.callbacks = value;
    }

    /**
     * Gets the value of the fingerprint property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFingerprint() {
	return fingerprint;
    }

    /**
     * Sets the value of the fingerprint property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFingerprint(String value) {
	this.fingerprint = value;
    }

}
