//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.27 at 10:15:51 AM PDT 
//


package com.gtnexus.appxpress.platform.module.model.design;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import com.google.common.base.Function;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}version"/>
 *         &lt;element ref="{}globalObjectType"/>
 *         &lt;element ref="{}name"/>
 *         &lt;element ref="{}description"/>
 *         &lt;element ref="{}uniqueIdentifier"/>
 *         &lt;element ref="{}designType"/>
 *         &lt;element ref="{}scalarField" maxOccurs="unbounded"/>
 *         &lt;element ref="{}linkField" maxOccurs="unbounded"/>
 *         &lt;element ref="{}workflowFeature"/>
 *         &lt;element ref="{}scriptingFeature"/>
 *         &lt;element ref="{}integrationFeature"/>
 *         &lt;element ref="{}navFeature"/>
 *         &lt;element ref="{}visibilityType"/>
 *         &lt;element ref="{}roleSecurity" maxOccurs="unbounded"/>
 *         &lt;element ref="{}codSection"/>
 *         &lt;element ref="{}schemaVers"/>
 *         &lt;element ref="{}apiVersion"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "version",
    "globalObjectType",
    "name",
    "description",
    "uniqueIdentifier",
    "designType",
    "scalarField",
    "linkField",
    "workflowFeature",
    "scriptingFeature",
    "integrationFeature",
    "navFeature",
    "visibilityType",
    "roleSecurity",
    "codSection",
    "schemaVers",
    "apiVersion"
})
@XmlRootElement(name = "CustomObjectDesignV110")
public class CustomObjectDesignV110 {

    @XmlElement(required = true)
    protected BigInteger version;
    @XmlElement(required = true)
    protected String globalObjectType;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String uniqueIdentifier;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String designType;
    @XmlElement(required = true)
    protected List<ScalarField> scalarField;
    @XmlElement(required = true)
    protected List<LinkField> linkField;
    @XmlElement(required = true)
    protected WorkflowFeature workflowFeature;
    @XmlElement(required = true)
    protected ScriptingFeature scriptingFeature;
    @XmlElement(required = true)
    protected IntegrationFeature integrationFeature;
    @XmlElement(required = true)
    protected NavFeature navFeature;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String visibilityType;
    @XmlElement(required = true)
    protected List<RoleSecurity> roleSecurity;
    @XmlElement(required = true)
    protected CodSection codSection;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String schemaVers;
    @XmlElement(required = true)
    protected BigInteger apiVersion;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersion(BigInteger value) {
        this.version = value;
    }

    /**
     * Gets the value of the globalObjectType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobalObjectType() {
        return globalObjectType;
    }

    /**
     * Sets the value of the globalObjectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalObjectType(String value) {
        this.globalObjectType = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the uniqueIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniqueIdentifier() {
        return uniqueIdentifier;
    }

    /**
     * Sets the value of the uniqueIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniqueIdentifier(String value) {
        this.uniqueIdentifier = value;
    }

    /**
     * Gets the value of the designType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesignType() {
        return designType;
    }

    /**
     * Sets the value of the designType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesignType(String value) {
        this.designType = value;
    }

    /**
     * Gets the value of the scalarField property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scalarField property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScalarField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScalarField }
     * 
     * 
     */
    public List<ScalarField> getScalarField() {
        if (scalarField == null) {
            scalarField = new ArrayList<ScalarField>();
        }
        return this.scalarField;
    }

    /**
     * Gets the value of the linkField property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the linkField property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinkField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LinkField }
     * 
     * 
     */
    public List<LinkField> getLinkField() {
        if (linkField == null) {
            linkField = new ArrayList<LinkField>();
        }
        return this.linkField;
    }

    /**
     * Gets the value of the workflowFeature property.
     * 
     * @return
     *     possible object is
     *     {@link WorkflowFeature }
     *     
     */
    public WorkflowFeature getWorkflowFeature() {
        return workflowFeature;
    }

    /**
     * Sets the value of the workflowFeature property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkflowFeature }
     *     
     */
    public void setWorkflowFeature(WorkflowFeature value) {
        this.workflowFeature = value;
    }

    /**
     * Gets the value of the scriptingFeature property.
     * 
     * @return
     *     possible object is
     *     {@link ScriptingFeature }
     *     
     */
    public ScriptingFeature getScriptingFeature() {
        return scriptingFeature;
    }

    /**
     * Sets the value of the scriptingFeature property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScriptingFeature }
     *     
     */
    public void setScriptingFeature(ScriptingFeature value) {
        this.scriptingFeature = value;
    }

    /**
     * Gets the value of the integrationFeature property.
     * 
     * @return
     *     possible object is
     *     {@link IntegrationFeature }
     *     
     */
    public IntegrationFeature getIntegrationFeature() {
        return integrationFeature;
    }

    /**
     * Sets the value of the integrationFeature property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntegrationFeature }
     *     
     */
    public void setIntegrationFeature(IntegrationFeature value) {
        this.integrationFeature = value;
    }

    /**
     * Gets the value of the navFeature property.
     * 
     * @return
     *     possible object is
     *     {@link NavFeature }
     *     
     */
    public NavFeature getNavFeature() {
        return navFeature;
    }

    /**
     * Sets the value of the navFeature property.
     * 
     * @param value
     *     allowed object is
     *     {@link NavFeature }
     *     
     */
    public void setNavFeature(NavFeature value) {
        this.navFeature = value;
    }

    /**
     * Gets the value of the visibilityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisibilityType() {
        return visibilityType;
    }

    /**
     * Sets the value of the visibilityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisibilityType(String value) {
        this.visibilityType = value;
    }

    /**
     * Gets the value of the roleSecurity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roleSecurity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoleSecurity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RoleSecurity }
     * 
     * 
     */
    public List<RoleSecurity> getRoleSecurity() {
        if (roleSecurity == null) {
            roleSecurity = new ArrayList<RoleSecurity>();
        }
        return this.roleSecurity;
    }

    /**
     * Gets the value of the codSection property.
     * 
     * @return
     *     possible object is
     *     {@link CodSection }
     *     
     */
    public CodSection getCodSection() {
        return codSection;
    }

    /**
     * Sets the value of the codSection property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodSection }
     *     
     */
    public void setCodSection(CodSection value) {
        this.codSection = value;
    }

    /**
     * Gets the value of the schemaVers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaVers() {
        return schemaVers;
    }

    /**
     * Sets the value of the schemaVers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaVers(String value) {
        this.schemaVers = value;
    }

    /**
     * Gets the value of the apiVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getApiVersion() {
        return apiVersion;
    }

    /**
     * Sets the value of the apiVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setApiVersion(BigInteger value) {
        this.apiVersion = value;
    }
    
}
