//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.21 at 02:11:26 PM EDT 
//

package com.gtnexus.appxpress.platform.module.model.design;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}dataKey"/>
 *         &lt;element ref="{}stringValue" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "dataKey", "stringValue" })
@XmlRootElement(name = "extendedData")
public class ExtendedData {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String dataKey;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String stringValue;

    /**
     * Gets the value of the dataKey property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDataKey() {
	return dataKey;
    }

    /**
     * Sets the value of the dataKey property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDataKey(String value) {
	this.dataKey = value;
    }

    /**
     * Gets the value of the stringValue property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStringValue() {
	return stringValue;
    }

    /**
     * Sets the value of the stringValue property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setStringValue(String value) {
	this.stringValue = value;
    }

}
