//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.23 at 04:58:37 PM EDT 
//


package com.gtnexus.appxpress.platform.module.model.design;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.gtnexus.appxpress.platform.module.model.design package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DownloadRuntimeEnabled_QNAME = new QName("", "downloadRuntimeEnabled");
    private final static QName _FileName_QNAME = new QName("", "fileName");
    private final static QName _InitialStatus_QNAME = new QName("", "initialStatus");
    private final static QName _FieldNumber_QNAME = new QName("", "fieldNumber");
    private final static QName _NumberOfDisplayColumns_QNAME = new QName("", "numberOfDisplayColumns");
    private final static QName _MimeType_QNAME = new QName("", "mimeType");
    private final static QName _StringValue_QNAME = new QName("", "stringValue");
    private final static QName _ApiVersion_QNAME = new QName("", "apiVersion");
    private final static QName _BusinessStatusField_QNAME = new QName("", "businessStatusField");
    private final static QName _Action_QNAME = new QName("", "action");
    private final static QName _State_QNAME = new QName("", "state");
    private final static QName _RevisionIncrementFunctionName_QNAME = new QName("", "revisionIncrementFunctionName");
    private final static QName _VisibilityType_QNAME = new QName("", "visibilityType");
    private final static QName _FieldMaskFunctionName_QNAME = new QName("", "fieldMaskFunctionName");
    private final static QName _FromState_QNAME = new QName("", "fromState");
    private final static QName _MutateOthersEnabled_QNAME = new QName("", "mutateOthersEnabled");
    private final static QName _Indexed_QNAME = new QName("", "indexed");
    private final static QName _FieldMaskingEnabled_QNAME = new QName("", "fieldMaskingEnabled");
    private final static QName _DesignType_QNAME = new QName("", "designType");
    private final static QName _DataType_QNAME = new QName("", "dataType");
    private final static QName _EventType_QNAME = new QName("", "eventType");
    private final static QName _Version_QNAME = new QName("", "version");
    private final static QName _FieldPosition_QNAME = new QName("", "fieldPosition");
    private final static QName _SystemDelete_QNAME = new QName("", "systemDelete");
    private final static QName _SchemaVers_QNAME = new QName("", "schemaVers");
    private final static QName _LandingOQL_QNAME = new QName("", "landingOQL");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _NavHeading_QNAME = new QName("", "navHeading");
    private final static QName _PreconditionFn_QNAME = new QName("", "preconditionFn");
    private final static QName _MaxLength_QNAME = new QName("", "maxLength");
    private final static QName _LicenseeField_QNAME = new QName("", "licenseeField");
    private final static QName _UseTableSupport_QNAME = new QName("", "useTableSupport");
    private final static QName _FieldName_QNAME = new QName("", "fieldName");
    private final static QName _RequiredDocStates_QNAME = new QName("", "requiredDocStates");
    private final static QName _Code_QNAME = new QName("", "code");
    private final static QName _Role_QNAME = new QName("", "role");
    private final static QName _Roles_QNAME = new QName("", "roles");
    private final static QName _IsCollection_QNAME = new QName("", "isCollection");
    private final static QName _MutateSelfEnabled_QNAME = new QName("", "mutateSelfEnabled");
    private final static QName _Description_QNAME = new QName("", "description");
    private final static QName _OnStateFn_QNAME = new QName("", "onStateFn");
    private final static QName _Enabled_QNAME = new QName("", "enabled");
    private final static QName _DataKey_QNAME = new QName("", "dataKey");
    private final static QName _ToState_QNAME = new QName("", "toState");
    private final static QName _AnchorOQL_QNAME = new QName("", "anchorOQL");
    private final static QName _RenderedOnUi_QNAME = new QName("", "renderedOnUi");
    private final static QName _UploadRuntimeEnabled_QNAME = new QName("", "uploadRuntimeEnabled");
    private final static QName _GlobalObjectType_QNAME = new QName("", "globalObjectType");
    private final static QName _EditRoles_QNAME = new QName("", "editRoles");
    private final static QName _LinkToDesign_QNAME = new QName("", "linkToDesign");
    private final static QName _UniqueIdentifier_QNAME = new QName("", "uniqueIdentifier");
    private final static QName _FunctionName_QNAME = new QName("", "functionName");
    private final static QName _PostTransitionFn_QNAME = new QName("", "postTransitionFn");
    private final static QName _SummaryField_QNAME = new QName("", "summaryField");
    private final static QName _DetailedDataType_QNAME = new QName("", "detailedDataType");
    private final static QName _TransactionType_QNAME = new QName("", "transactionType");
    private final static QName _ObjectQueryEnabled_QNAME = new QName("", "objectQueryEnabled");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.gtnexus.appxpress.platform.module.model.design
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ScriptingFeature }
     * 
     */
    public ScriptingFeature createScriptingFeature() {
        return new ScriptingFeature();
    }

    /**
     * Create an instance of {@link ScalarField }
     * 
     */
    public ScalarField createScalarField() {
        return new ScalarField();
    }

    /**
     * Create an instance of {@link ExtendedData }
     * 
     */
    public ExtendedData createExtendedData() {
        return new ExtendedData();
    }

    /**
     * Create an instance of {@link Workflow }
     * 
     */
    public Workflow createWorkflow() {
        return new Workflow();
    }

    /**
     * Create an instance of {@link Step }
     * 
     */
    public Step createStep() {
        return new Step();
    }

    /**
     * Create an instance of {@link Transition }
     * 
     */
    public Transition createTransition() {
        return new Transition();
    }

    /**
     * Create an instance of {@link AttachmentFeature }
     * 
     */
    public AttachmentFeature createAttachmentFeature() {
        return new AttachmentFeature();
    }

    /**
     * Create an instance of {@link WorkflowFeature }
     * 
     */
    public WorkflowFeature createWorkflowFeature() {
        return new WorkflowFeature();
    }

    /**
     * Create an instance of {@link EventField }
     * 
     */
    public EventField createEventField() {
        return new EventField();
    }

    /**
     * Create an instance of {@link PdfFeature }
     * 
     */
    public PdfFeature createPdfFeature() {
        return new PdfFeature();
    }

    /**
     * Create an instance of {@link CustomObjectDesignV110 }
     * 
     */
    public CustomObjectDesignV110 createCustomObjectDesignV110() {
        return new CustomObjectDesignV110();
    }

    /**
     * Create an instance of {@link LinkField }
     * 
     */
    public LinkField createLinkField() {
        return new LinkField();
    }

    /**
     * Create an instance of {@link ReportingFeature }
     * 
     */
    public ReportingFeature createReportingFeature() {
        return new ReportingFeature();
    }

    /**
     * Create an instance of {@link IntegrationFeature }
     * 
     */
    public IntegrationFeature createIntegrationFeature() {
        return new IntegrationFeature();
    }

    /**
     * Create an instance of {@link NavFeature }
     * 
     */
    public NavFeature createNavFeature() {
        return new NavFeature();
    }

    /**
     * Create an instance of {@link Anchor }
     * 
     */
    public Anchor createAnchor() {
        return new Anchor();
    }

    /**
     * Create an instance of {@link RoleSecurity }
     * 
     */
    public RoleSecurity createRoleSecurity() {
        return new RoleSecurity();
    }

    /**
     * Create an instance of {@link CodSection }
     * 
     */
    public CodSection createCodSection() {
        return new CodSection();
    }

    /**
     * Create an instance of {@link CodExtensionPoint }
     * 
     */
    public CodExtensionPoint createCodExtensionPoint() {
        return new CodExtensionPoint();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "downloadRuntimeEnabled")
    public JAXBElement<Boolean> createDownloadRuntimeEnabled(Boolean value) {
        return new JAXBElement<Boolean>(_DownloadRuntimeEnabled_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fileName")
    public JAXBElement<String> createFileName(String value) {
        return new JAXBElement<String>(_FileName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "initialStatus")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createInitialStatus(String value) {
        return new JAXBElement<String>(_InitialStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fieldNumber")
    public JAXBElement<BigInteger> createFieldNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_FieldNumber_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "numberOfDisplayColumns")
    public JAXBElement<BigInteger> createNumberOfDisplayColumns(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumberOfDisplayColumns_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mimeType")
    public JAXBElement<String> createMimeType(String value) {
        return new JAXBElement<String>(_MimeType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "stringValue")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createStringValue(String value) {
        return new JAXBElement<String>(_StringValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "apiVersion")
    public JAXBElement<BigInteger> createApiVersion(BigInteger value) {
        return new JAXBElement<BigInteger>(_ApiVersion_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "businessStatusField")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createBusinessStatusField(String value) {
        return new JAXBElement<String>(_BusinessStatusField_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "action")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAction(String value) {
        return new JAXBElement<String>(_Action_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "state")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createState(String value) {
        return new JAXBElement<String>(_State_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "revisionIncrementFunctionName")
    public JAXBElement<String> createRevisionIncrementFunctionName(String value) {
        return new JAXBElement<String>(_RevisionIncrementFunctionName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "visibilityType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createVisibilityType(String value) {
        return new JAXBElement<String>(_VisibilityType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fieldMaskFunctionName")
    public JAXBElement<String> createFieldMaskFunctionName(String value) {
        return new JAXBElement<String>(_FieldMaskFunctionName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fromState")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFromState(String value) {
        return new JAXBElement<String>(_FromState_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mutateOthersEnabled")
    public JAXBElement<String> createMutateOthersEnabled(String value) {
        return new JAXBElement<String>(_MutateOthersEnabled_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "indexed")
    public JAXBElement<Boolean> createIndexed(Boolean value) {
        return new JAXBElement<Boolean>(_Indexed_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fieldMaskingEnabled")
    public JAXBElement<String> createFieldMaskingEnabled(String value) {
        return new JAXBElement<String>(_FieldMaskingEnabled_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "designType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDesignType(String value) {
        return new JAXBElement<String>(_DesignType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dataType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDataType(String value) {
        return new JAXBElement<String>(_DataType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "eventType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createEventType(String value) {
        return new JAXBElement<String>(_EventType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "version")
    public JAXBElement<BigInteger> createVersion(BigInteger value) {
        return new JAXBElement<BigInteger>(_Version_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fieldPosition")
    public JAXBElement<BigInteger> createFieldPosition(BigInteger value) {
        return new JAXBElement<BigInteger>(_FieldPosition_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "systemDelete")
    public JAXBElement<Boolean> createSystemDelete(Boolean value) {
        return new JAXBElement<Boolean>(_SystemDelete_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "schemaVers")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSchemaVers(String value) {
        return new JAXBElement<String>(_SchemaVers_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "landingOQL")
    public JAXBElement<String> createLandingOQL(String value) {
        return new JAXBElement<String>(_LandingOQL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "navHeading")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createNavHeading(String value) {
        return new JAXBElement<String>(_NavHeading_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "preconditionFn")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPreconditionFn(String value) {
        return new JAXBElement<String>(_PreconditionFn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "maxLength")
    public JAXBElement<BigInteger> createMaxLength(BigInteger value) {
        return new JAXBElement<BigInteger>(_MaxLength_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "licenseeField")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLicenseeField(String value) {
        return new JAXBElement<String>(_LicenseeField_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "useTableSupport")
    public JAXBElement<Boolean> createUseTableSupport(Boolean value) {
        return new JAXBElement<Boolean>(_UseTableSupport_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fieldName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFieldName(String value) {
        return new JAXBElement<String>(_FieldName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "requiredDocStates")
    public JAXBElement<String> createRequiredDocStates(String value) {
        return new JAXBElement<String>(_RequiredDocStates_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "code")
    public JAXBElement<String> createCode(String value) {
        return new JAXBElement<String>(_Code_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "role")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createRole(String value) {
        return new JAXBElement<String>(_Role_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "roles")
    public JAXBElement<String> createRoles(String value) {
        return new JAXBElement<String>(_Roles_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "isCollection")
    public JAXBElement<Boolean> createIsCollection(Boolean value) {
        return new JAXBElement<Boolean>(_IsCollection_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mutateSelfEnabled")
    public JAXBElement<String> createMutateSelfEnabled(String value) {
        return new JAXBElement<String>(_MutateSelfEnabled_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "onStateFn")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOnStateFn(String value) {
        return new JAXBElement<String>(_OnStateFn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "enabled")
    public JAXBElement<Boolean> createEnabled(Boolean value) {
        return new JAXBElement<Boolean>(_Enabled_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dataKey")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDataKey(String value) {
        return new JAXBElement<String>(_DataKey_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "toState")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createToState(String value) {
        return new JAXBElement<String>(_ToState_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "anchorOQL")
    public JAXBElement<String> createAnchorOQL(String value) {
        return new JAXBElement<String>(_AnchorOQL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "renderedOnUi")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createRenderedOnUi(String value) {
        return new JAXBElement<String>(_RenderedOnUi_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "uploadRuntimeEnabled")
    public JAXBElement<Boolean> createUploadRuntimeEnabled(Boolean value) {
        return new JAXBElement<Boolean>(_UploadRuntimeEnabled_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "globalObjectType")
    public JAXBElement<String> createGlobalObjectType(String value) {
        return new JAXBElement<String>(_GlobalObjectType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "editRoles")
    public JAXBElement<String> createEditRoles(String value) {
        return new JAXBElement<String>(_EditRoles_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "linkToDesign")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLinkToDesign(String value) {
        return new JAXBElement<String>(_LinkToDesign_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "uniqueIdentifier")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createUniqueIdentifier(String value) {
        return new JAXBElement<String>(_UniqueIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "functionName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFunctionName(String value) {
        return new JAXBElement<String>(_FunctionName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "postTransitionFn")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPostTransitionFn(String value) {
        return new JAXBElement<String>(_PostTransitionFn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "summaryField")
    public JAXBElement<Boolean> createSummaryField(Boolean value) {
        return new JAXBElement<Boolean>(_SummaryField_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "detailedDataType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDetailedDataType(String value) {
        return new JAXBElement<String>(_DetailedDataType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "transactionType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTransactionType(String value) {
        return new JAXBElement<String>(_TransactionType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "objectQueryEnabled")
    public JAXBElement<String> createObjectQueryEnabled(String value) {
        return new JAXBElement<String>(_ObjectQueryEnabled_QNAME, String.class, null, value);
    }

}
