//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.23 at 04:58:37 PM EDT 
//


package com.gtnexus.appxpress.platform.module.model.design;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}editRoles"/>
 *         &lt;element ref="{}onStateFn" minOccurs="0"/>
 *         &lt;element ref="{}state"/>
 *         &lt;element ref="{}systemDelete"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "editRoles",
    "onStateFn",
    "state",
    "systemDelete"
})
@XmlRootElement(name = "step")
public class Step {

    @XmlElement(required = true)
    protected String editRoles;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String onStateFn;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String state;
    protected boolean systemDelete;

    /**
     * Gets the value of the editRoles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEditRoles() {
        return editRoles;
    }

    /**
     * Sets the value of the editRoles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEditRoles(String value) {
        this.editRoles = value;
    }

    /**
     * Gets the value of the onStateFn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnStateFn() {
        return onStateFn;
    }

    /**
     * Sets the value of the onStateFn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnStateFn(String value) {
        this.onStateFn = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the systemDelete property.
     * 
     */
    public boolean isSystemDelete() {
        return systemDelete;
    }

    /**
     * Sets the value of the systemDelete property.
     * 
     */
    public void setSystemDelete(boolean value) {
        this.systemDelete = value;
    }

}
