#!bin/bash

function showOptions ( )
{
	echo ""
	echo "usage: bash Marvin [options]"
	echo ""
	echo "	-repository		set default repository to clone from"
	echo "	-pm				set default Platform Module Folder"
	echo "	-branch			set default branch in repository to clone from"
	echo "	-clear 			clear property file of defaults"
	echo "	-customer		set customer file path of desired platform module"
}
#######################################################
function rewritePropertyFile ( )
{
	rm marvin_data.properties
	touch "marvin_data.properties"
	echo "p_repository=$repo" >> $propFile
	echo "p_folder=$folder" >> $propFile
	echo "p_branch=$branch" >> $propFile
	echo "p_customer=$customer" >> $propFile
}
#######################################################
###############Set Property File#######################
#######################################################
propFile=marvin_data.properties
if [ ! -f "$propFile" ] ; then
    touch "$propFile"
fi
#######################################################
###############Set properties##########################
#######################################################
if [ -f marvin_data.properties ] ; then
	. marvin_data.properties
fi
repo="$p_repository"
folder="$p_folder"
branch="$p_branch"
customer="$p_customer"

#######################################################
################Check for set Options##################
#######################################################
	#Set repo variable third arg
	#program will use this as a default to clone from
	if [ "$1" == "-repository" ] ; then
		if [[ -n $2 ]] ; then
			repo=$2
			rewritePropertyFile
			echo "Set repository property"
		else
			echo "Need to add name of repository"
		fi
		exit 0
	fi
	#Set folder name variable third arg
	#program will use this as a default folder to create a zip
	if [ "$1" == "-pm" ] ; then
		if [[ -n $2 ]] ; then
			folder=$2
			rewritePropertyFile
			echo "Set source folder property"
		else
			echo "Need to add name of folder"
		fi
		exit 0
	fi
	#Set default branch of repository to clone from
	if [ "$1" == "-branch" ] ; then
		if [[ -n $2 ]] ; then
			branch=$2
			rewritePropertyFile
			echo "Set repository branch property"
		else
			echo "Need to add name of branch in repository"
		fi
		exit 0
	fi
	#Set customer path of platform module folder
	if [ "$1" == "-customer" ] ; then
		if [[ -n $2 ]] ; then
			customer=$2
			rewritePropertyFile
			echo "Set customer path"
		else
			echo "Need to add name of branch in repository"
		fi
		exit 0
	fi

if [[ $1 == "-help" ]] ; then
	showOptions
	exit 0
elif [[ $1 == "-clear" ]] ; then
	rm marvin_data.properties
	echo "Property file cleared"
	exit 0
fi

echo "Default Repository : $repo "
echo "Default Source Folder : $folder "
echo "Default branch :	$branch"
echo "Default customer : $customer"
##############################################
if [ ! -d .git ] ; then
	git init
fi 

if [ -z "$repo" ] ; then
	read -p "Enter repository url: " repo 
fi
	
if [ -z "$branch" ] ; then
	read -p "Enter branch of repository: " branch
fi

git remote remove stash 2>/dev/null
git remote add stash $repo
git pull stash "$branch"

if cd lib 2>/dev/null; then
	cd ..
else
	echo ""
	echo "Directory did not pull down correct - cannot find lib folder."
	echo "Make sure GIT repository URL is correct and branch $branch exists"
	exit 0
fi
#################################################
##############Run import util####################
#################################################

if [ -z "$customer" ] ; then
	read -p "Enter customer: " customer
fi

if [ -z "$folder" ] ; then
	read -p "Enter platform module folder: " folder
fi

if [ ! -d customer/$customer ] ; then
	echo "Cannot find customer $customer folder"
	exit 0
fi
	
if [ ! -d customer/$customer/$folder ] ; then
	echo "Cannot find custom object $folder in customer folder $customer"
	exit 0
fi

##Before running jar, remove previous zip if there#
##Also, reset working dir to match git and clean ##
##customer folder##################################

zip=".zip"
zipFolder=$folder$zip
echo $zipFolder
if [ -f "$zipFolder" ] ; then
	rm -rf $zipFolder
fi

branchReset="stash/"$branch
echo $branchReset

cd customer
cd $customer

git reset --hard $branchReset
git clean -f -d $folder

cd ..
cd ..

java -jar MarvinImportUtil.jar $customer $folder

exit 0
###########################################################################