//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 05:19:55 PM EDT 
//

package com.gtnexus.pmm.app.platform.module.model.customlink;

import java.math.BigInteger;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the
 * com.gtnexus.appxpress.platform.module.model.customlink package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RedirectUrl_QNAME = new QName("", "redirectUrl");
    private final static QName _CreatorId_QNAME = new QName("", "creatorId");
    private final static QName _CustomLinkId_QNAME = new QName("", "customLinkId");
    private final static QName _LocalizationKey_QNAME = new QName("", "localizationKey");
    private final static QName _Type_QNAME = new QName("", "type");
    private final static QName _Url_QNAME = new QName("", "url");
    private final static QName _CreateTimestamp_QNAME = new QName("", "createTimestamp");
    private final static QName _ModifyTimestamp_QNAME = new QName("", "modifyTimestamp");
    private final static QName _Uid_QNAME = new QName("", "uid");
    private final static QName _LicenseeOnly_QNAME = new QName("", "licenseeOnly");
    private final static QName _ApiVersion_QNAME = new QName("", "apiVersion");
    private final static QName _PlatformModuleId_QNAME = new QName("", "platformModuleId");
    private final static QName _PlatformModuleType_QNAME = new QName("", "platformModuleType");
    private final static QName _UserModRev_QNAME = new QName("", "userModRev");
    private final static QName _Fingerprint_QNAME = new QName("", "fingerprint");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _Self_QNAME = new QName("", "self");
    private final static QName _LinkType_QNAME = new QName("", "linkType");
    private final static QName _Location_QNAME = new QName("", "location");
    private final static QName _Status_QNAME = new QName("", "status");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema
     * derived classes for package:
     * com.gtnexus.appxpress.platform.module.model.customlink
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CustomLinkD1 }
     * 
     */
    public CustomLinkD1 createCUSTOMLINKD1() {
	return new CustomLinkD1();
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadata() {
	return new Metadata();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "redirectUrl")
    public JAXBElement<String> createRedirectUrl(String value) {
	return new JAXBElement<String>(_RedirectUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger
     * }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "creatorId")
    public JAXBElement<BigInteger> createCreatorId(BigInteger value) {
	return new JAXBElement<BigInteger>(_CreatorId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger
     * }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "customLinkId")
    public JAXBElement<BigInteger> createCustomLinkId(BigInteger value) {
	return new JAXBElement<BigInteger>(_CustomLinkId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "localizationKey")
    public JAXBElement<String> createLocalizationKey(String value) {
	return new JAXBElement<String>(_LocalizationKey_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "type")
    public JAXBElement<String> createType(String value) {
	return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "url")
    public JAXBElement<String> createUrl(String value) {
	return new JAXBElement<String>(_Url_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "createTimestamp")
    public JAXBElement<String> createCreateTimestamp(String value) {
	return new JAXBElement<String>(_CreateTimestamp_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "modifyTimestamp")
    public JAXBElement<String> createModifyTimestamp(String value) {
	return new JAXBElement<String>(_ModifyTimestamp_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger
     * }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "uid")
    public JAXBElement<BigInteger> createUid(BigInteger value) {
	return new JAXBElement<BigInteger>(_Uid_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "licenseeOnly")
    public JAXBElement<String> createLicenseeOnly(String value) {
	return new JAXBElement<String>(_LicenseeOnly_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger
     * }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "apiVersion")
    public JAXBElement<BigInteger> createApiVersion(BigInteger value) {
	return new JAXBElement<BigInteger>(_ApiVersion_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger
     * }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "platformModuleId")
    public JAXBElement<BigInteger> createPlatformModuleId(BigInteger value) {
	return new JAXBElement<BigInteger>(_PlatformModuleId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "platformModuleType")
    public JAXBElement<String> createPlatformModuleType(String value) {
	return new JAXBElement<String>(_PlatformModuleType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger
     * }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "userModRev")
    public JAXBElement<BigInteger> createUserModRev(BigInteger value) {
	return new JAXBElement<BigInteger>(_UserModRev_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fingerprint")
    public JAXBElement<String> createFingerprint(String value) {
	return new JAXBElement<String>(_Fingerprint_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
	return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "self")
    public JAXBElement<String> createSelf(String value) {
	return new JAXBElement<String>(_Self_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "linkType")
    public JAXBElement<String> createLinkType(String value) {
	return new JAXBElement<String>(_LinkType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "location")
    public JAXBElement<String> createLocation(String value) {
	return new JAXBElement<String>(_Location_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "status")
    public JAXBElement<String> createStatus(String value) {
	return new JAXBElement<String>(_Status_QNAME, String.class, null, value);
    }

}
