//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.23 at 01:15:37 PM EDT 
//

package com.gtnexus.appxpress.platform.module.model.customaction;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}__metadata"/>
 *         &lt;element ref="{}type"/>
 *         &lt;element ref="{}uid"/>
 *         &lt;element ref="{}customActionId"/>
 *         &lt;element ref="{}platformModuleId"/>
 *         &lt;element ref="{}platformModuleType"/>
 *         &lt;element ref="{}name"/>
 *         &lt;element ref="{}status"/>
 *         &lt;element ref="{}docType"/>
 *         &lt;element ref="{}apiVersion"/>
 *         &lt;element ref="{}roles"/>
 *         &lt;element ref="{}oql"/>
 *         &lt;element ref="{}hasActionFn"/>
 *         &lt;element ref="{}executeFn"/>
 *         &lt;element ref="{}fingerprint"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "metadata", "type", "uid", "customActionId", "platformModuleId", "platformModuleType",
	"name", "status", "docType", "apiVersion", "roles", "oql", "hasActionFn", "executeFn", "fingerprint" })
@XmlRootElement(name = "CUSTOMACTIOND1")
public class CustomActionD1 {

    @XmlElement(name = "__metadata", required = true)
    protected Metadata metadata;
    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    protected BigInteger uid;
    @XmlElement(required = true)
    protected BigInteger customActionId;
    @XmlElement(required = true)
    protected BigInteger platformModuleId;
    @XmlElement(required = true)
    protected String platformModuleType;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(required = true)
    protected String docType;
    @XmlElement(required = true)
    protected BigInteger apiVersion;
    @XmlElement(required = true)
    protected String roles;
    @XmlElement(required = true)
    protected String oql;
    @XmlElement(required = true)
    protected String hasActionFn;
    @XmlElement(required = true)
    protected String executeFn;
    @XmlElement(required = true)
    protected String fingerprint;

    /**
     * Gets the value of the metadata property.
     * 
     * @return possible object is {@link Metadata }
     * 
     */
    public Metadata getMetadata() {
	return metadata;
    }

    /**
     * Sets the value of the metadata property.
     * 
     * @param value
     *            allowed object is {@link Metadata }
     * 
     */
    public void setMetadata(Metadata value) {
	this.metadata = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getType() {
	return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setType(String value) {
	this.type = value;
    }

    /**
     * Gets the value of the uid property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getUid() {
	return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setUid(BigInteger value) {
	this.uid = value;
    }

    /**
     * Gets the value of the customActionId property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getCustomActionId() {
	return customActionId;
    }

    /**
     * Sets the value of the customActionId property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setCustomActionId(BigInteger value) {
	this.customActionId = value;
    }

    /**
     * Gets the value of the platformModuleId property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getPlatformModuleId() {
	return platformModuleId;
    }

    /**
     * Sets the value of the platformModuleId property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setPlatformModuleId(BigInteger value) {
	this.platformModuleId = value;
    }

    /**
     * Gets the value of the platformModuleType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPlatformModuleType() {
	return platformModuleType;
    }

    /**
     * Sets the value of the platformModuleType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPlatformModuleType(String value) {
	this.platformModuleType = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getName() {
	return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setName(String value) {
	this.name = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStatus() {
	return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setStatus(String value) {
	this.status = value;
    }

    /**
     * Gets the value of the docType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDocType() {
	return docType;
    }

    /**
     * Sets the value of the docType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDocType(String value) {
	this.docType = value;
    }

    /**
     * Gets the value of the apiVersion property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getApiVersion() {
	return apiVersion;
    }

    /**
     * Sets the value of the apiVersion property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setApiVersion(BigInteger value) {
	this.apiVersion = value;
    }

    /**
     * Gets the value of the roles property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRoles() {
	return roles;
    }

    /**
     * Sets the value of the roles property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRoles(String value) {
	this.roles = value;
    }

    /**
     * Gets the value of the oql property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getOql() {
	return oql;
    }

    /**
     * Sets the value of the oql property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setOql(String value) {
	this.oql = value;
    }

    /**
     * Gets the value of the hasActionFn property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getHasActionFn() {
	return hasActionFn;
    }

    /**
     * Sets the value of the hasActionFn property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setHasActionFn(String value) {
	this.hasActionFn = value;
    }

    /**
     * Gets the value of the executeFn property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getExecuteFn() {
	return executeFn;
    }

    /**
     * Sets the value of the executeFn property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setExecuteFn(String value) {
	this.executeFn = value;
    }

    /**
     * Gets the value of the fingerprint property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFingerprint() {
	return fingerprint;
    }

    /**
     * Sets the value of the fingerprint property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFingerprint(String value) {
	this.fingerprint = value;
    }

}
