//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.22 at 04:41:28 PM EDT 
//


package com.gtnexus.appxpress.platform.module.model.customaction;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="__metadata">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="apiVersion" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="uid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="createTimestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="modifyTimestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="userModRev" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="creatorId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="fingerprint" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="redirectUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="self" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="uid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="customActionId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="platformModuleId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="platformModuleType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="docType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="apiVersion" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="roles" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="executeFn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fingerprint" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "metadata",
    "type",
    "uid",
    "customActionId",
    "platformModuleId",
    "platformModuleType",
    "name",
    "status",
    "docType",
    "apiVersion",
    "roles",
    "executeFn",
    "fingerprint"
})
@XmlRootElement(name = "CUSTOMACTIOND1")
public class CustomActionD1 {

    @XmlElement(name = "__metadata", required = true)
    protected CustomActionD1 .Metadata metadata;
    @XmlElement(required = true)
    protected String type;
    protected int uid;
    protected int customActionId;
    protected int platformModuleId;
    @XmlElement(required = true)
    protected String platformModuleType;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(required = true)
    protected String docType;
    protected int apiVersion;
    @XmlElement(required = true)
    protected String roles;
    @XmlElement(required = true)
    protected String executeFn;
    @XmlElement(required = true)
    protected String fingerprint;

    /**
     * Gets the value of the metadata property.
     * 
     * @return
     *     possible object is
     *     {@link CustomActionD1 .Metadata }
     *     
     */
    public CustomActionD1 .Metadata getMetadata() {
        return metadata;
    }

    /**
     * Sets the value of the metadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomActionD1 .Metadata }
     *     
     */
    public void setMetadata(CustomActionD1 .Metadata value) {
        this.metadata = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the uid property.
     * 
     */
    public int getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     */
    public void setUid(int value) {
        this.uid = value;
    }

    /**
     * Gets the value of the customActionId property.
     * 
     */
    public int getCustomActionId() {
        return customActionId;
    }

    /**
     * Sets the value of the customActionId property.
     * 
     */
    public void setCustomActionId(int value) {
        this.customActionId = value;
    }

    /**
     * Gets the value of the platformModuleId property.
     * 
     */
    public int getPlatformModuleId() {
        return platformModuleId;
    }

    /**
     * Sets the value of the platformModuleId property.
     * 
     */
    public void setPlatformModuleId(int value) {
        this.platformModuleId = value;
    }

    /**
     * Gets the value of the platformModuleType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatformModuleType() {
        return platformModuleType;
    }

    /**
     * Sets the value of the platformModuleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatformModuleType(String value) {
        this.platformModuleType = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the docType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocType() {
        return docType;
    }

    /**
     * Sets the value of the docType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocType(String value) {
        this.docType = value;
    }

    /**
     * Gets the value of the apiVersion property.
     * 
     */
    public int getApiVersion() {
        return apiVersion;
    }

    /**
     * Sets the value of the apiVersion property.
     * 
     */
    public void setApiVersion(int value) {
        this.apiVersion = value;
    }

    /**
     * Gets the value of the roles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoles() {
        return roles;
    }

    /**
     * Sets the value of the roles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoles(String value) {
        this.roles = value;
    }

    /**
     * Gets the value of the executeFn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExecuteFn() {
        return executeFn;
    }

    /**
     * Sets the value of the executeFn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExecuteFn(String value) {
        this.executeFn = value;
    }

    /**
     * Gets the value of the fingerprint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFingerprint() {
        return fingerprint;
    }

    /**
     * Sets the value of the fingerprint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFingerprint(String value) {
        this.fingerprint = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="apiVersion" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="uid" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="createTimestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="modifyTimestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="userModRev" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="creatorId" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="fingerprint" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="redirectUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="self" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "apiVersion",
        "type",
        "uid",
        "createTimestamp",
        "modifyTimestamp",
        "status",
        "userModRev",
        "creatorId",
        "fingerprint",
        "redirectUrl",
        "self"
    })
    public static class Metadata {

        protected int apiVersion;
        @XmlElement(required = true)
        protected String type;
        protected int uid;
        @XmlElement(required = true)
        protected String createTimestamp;
        @XmlElement(required = true)
        protected String modifyTimestamp;
        @XmlElement(required = true)
        protected String status;
        protected int userModRev;
        protected int creatorId;
        @XmlElement(required = true)
        protected String fingerprint;
        @XmlElement(required = true)
        protected String redirectUrl;
        @XmlElement(required = true)
        protected String self;

        /**
         * Gets the value of the apiVersion property.
         * 
         */
        public int getApiVersion() {
            return apiVersion;
        }

        /**
         * Sets the value of the apiVersion property.
         * 
         */
        public void setApiVersion(int value) {
            this.apiVersion = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the uid property.
         * 
         */
        public int getUid() {
            return uid;
        }

        /**
         * Sets the value of the uid property.
         * 
         */
        public void setUid(int value) {
            this.uid = value;
        }

        /**
         * Gets the value of the createTimestamp property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCreateTimestamp() {
            return createTimestamp;
        }

        /**
         * Sets the value of the createTimestamp property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCreateTimestamp(String value) {
            this.createTimestamp = value;
        }

        /**
         * Gets the value of the modifyTimestamp property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getModifyTimestamp() {
            return modifyTimestamp;
        }

        /**
         * Sets the value of the modifyTimestamp property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setModifyTimestamp(String value) {
            this.modifyTimestamp = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the userModRev property.
         * 
         */
        public int getUserModRev() {
            return userModRev;
        }

        /**
         * Sets the value of the userModRev property.
         * 
         */
        public void setUserModRev(int value) {
            this.userModRev = value;
        }

        /**
         * Gets the value of the creatorId property.
         * 
         */
        public int getCreatorId() {
            return creatorId;
        }

        /**
         * Sets the value of the creatorId property.
         * 
         */
        public void setCreatorId(int value) {
            this.creatorId = value;
        }

        /**
         * Gets the value of the fingerprint property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFingerprint() {
            return fingerprint;
        }

        /**
         * Sets the value of the fingerprint property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFingerprint(String value) {
            this.fingerprint = value;
        }

        /**
         * Gets the value of the redirectUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRedirectUrl() {
            return redirectUrl;
        }

        /**
         * Sets the value of the redirectUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRedirectUrl(String value) {
            this.redirectUrl = value;
        }

        /**
         * Gets the value of the self property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSelf() {
            return self;
        }

        /**
         * Sets the value of the self property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSelf(String value) {
            this.self = value;
        }

    }

}
