//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.21 at 02:11:26 PM EDT 
//

package com.gtnexus.pmm.platform.module.model.design;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}fieldName"/>
 *         &lt;element ref="{}fieldNumber"/>
 *         &lt;element ref="{}fieldPosition"/>
 *         &lt;element ref="{}linkToDesign"/>
 *         &lt;element ref="{}renderedOnUi"/>
 *         &lt;element ref="{}isCollection"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "fieldName", "fieldNumber", "fieldPosition", "linkToDesign", "renderedOnUi",
	"isCollection" })
@XmlRootElement(name = "linkField")
public class LinkField {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String fieldName;
    @XmlElement(required = true)
    protected BigInteger fieldNumber;
    @XmlElement(required = true)
    protected BigInteger fieldPosition;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String linkToDesign;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String renderedOnUi;
    protected boolean isCollection;

    /**
     * Gets the value of the fieldName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFieldName() {
	return fieldName;
    }

    /**
     * Sets the value of the fieldName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFieldName(String value) {
	this.fieldName = value;
    }

    /**
     * Gets the value of the fieldNumber property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getFieldNumber() {
	return fieldNumber;
    }

    /**
     * Sets the value of the fieldNumber property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setFieldNumber(BigInteger value) {
	this.fieldNumber = value;
    }

    /**
     * Gets the value of the fieldPosition property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getFieldPosition() {
	return fieldPosition;
    }

    /**
     * Sets the value of the fieldPosition property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setFieldPosition(BigInteger value) {
	this.fieldPosition = value;
    }

    /**
     * Gets the value of the linkToDesign property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLinkToDesign() {
	return linkToDesign;
    }

    /**
     * Sets the value of the linkToDesign property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLinkToDesign(String value) {
	this.linkToDesign = value;
    }

    /**
     * Gets the value of the renderedOnUi property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRenderedOnUi() {
	return renderedOnUi;
    }

    /**
     * Sets the value of the renderedOnUi property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRenderedOnUi(String value) {
	this.renderedOnUi = value;
    }

    /**
     * Gets the value of the isCollection property.
     * 
     */
    public boolean isIsCollection() {
	return isCollection;
    }

    /**
     * Sets the value of the isCollection property.
     * 
     */
    public void setIsCollection(boolean value) {
	this.isCollection = value;
    }

}
