//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 05:19:55 PM EDT 
//


package com.gtnexus.appxpress.platform.module.model.customlink;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}__metadata"/>
 *         &lt;element ref="{}type"/>
 *         &lt;element ref="{}uid"/>
 *         &lt;element ref="{}customLinkId"/>
 *         &lt;element ref="{}platformModuleId"/>
 *         &lt;element ref="{}platformModuleType"/>
 *         &lt;element ref="{}name"/>
 *         &lt;element ref="{}url"/>
 *         &lt;element ref="{}status"/>
 *         &lt;element ref="{}localizationKey"/>
 *         &lt;element ref="{}licenseeOnly"/>
 *         &lt;element ref="{}linkType"/>
 *         &lt;element ref="{}location"/>
 *         &lt;element ref="{}fingerprint"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "metadata",
    "type",
    "uid",
    "customLinkId",
    "platformModuleId",
    "platformModuleType",
    "name",
    "url",
    "status",
    "localizationKey",
    "licenseeOnly",
    "linkType",
    "location",
    "fingerprint"
})
@XmlRootElement(name = "CUSTOMLINKD1")
public class CustomLinkD1 {

    @XmlElement(name = "__metadata", required = true)
    protected Metadata metadata;
    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    protected BigInteger uid;
    @XmlElement(required = true)
    protected BigInteger customLinkId;
    @XmlElement(required = true)
    protected BigInteger platformModuleId;
    @XmlElement(required = true)
    protected String platformModuleType;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String url;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(required = true)
    protected String localizationKey;
    @XmlElement(required = true)
    protected String licenseeOnly;
    @XmlElement(required = true)
    protected String linkType;
    @XmlElement(required = true)
    protected String location;
    @XmlElement(required = true)
    protected String fingerprint;

    /**
     * Gets the value of the metadata property.
     * 
     * @return
     *     possible object is
     *     {@link Metadata }
     *     
     */
    public Metadata getMetadata() {
        return metadata;
    }

    /**
     * Sets the value of the metadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Metadata }
     *     
     */
    public void setMetadata(Metadata value) {
        this.metadata = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUid(BigInteger value) {
        this.uid = value;
    }

    /**
     * Gets the value of the customLinkId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCustomLinkId() {
        return customLinkId;
    }

    /**
     * Sets the value of the customLinkId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCustomLinkId(BigInteger value) {
        this.customLinkId = value;
    }

    /**
     * Gets the value of the platformModuleId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPlatformModuleId() {
        return platformModuleId;
    }

    /**
     * Sets the value of the platformModuleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPlatformModuleId(BigInteger value) {
        this.platformModuleId = value;
    }

    /**
     * Gets the value of the platformModuleType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatformModuleType() {
        return platformModuleType;
    }

    /**
     * Sets the value of the platformModuleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatformModuleType(String value) {
        this.platformModuleType = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the localizationKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalizationKey() {
        return localizationKey;
    }

    /**
     * Sets the value of the localizationKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalizationKey(String value) {
        this.localizationKey = value;
    }

    /**
     * Gets the value of the licenseeOnly property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenseeOnly() {
        return licenseeOnly;
    }

    /**
     * Sets the value of the licenseeOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenseeOnly(String value) {
        this.licenseeOnly = value;
    }

    /**
     * Gets the value of the linkType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkType() {
        return linkType;
    }

    /**
     * Sets the value of the linkType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkType(String value) {
        this.linkType = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the fingerprint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFingerprint() {
        return fingerprint;
    }

    /**
     * Sets the value of the fingerprint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFingerprint(String value) {
        this.fingerprint = value;
    }

}
