//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.22 at 04:47:37 PM EDT 
//

package com.gtnexus.pmm.platform.module.model.platformmodule;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}topicName"/>
 *         &lt;element ref="{}notificationConfiguration"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "topicName", "notificationConfiguration" })
@XmlRootElement(name = "notificationTopic")
public class NotificationTopic {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String topicName;
    @XmlElement(required = true)
    protected NotificationConfiguration notificationConfiguration;

    /**
     * Gets the value of the topicName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTopicName() {
	return topicName;
    }

    /**
     * Sets the value of the topicName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTopicName(String value) {
	this.topicName = value;
    }

    /**
     * Gets the value of the notificationConfiguration property.
     * 
     * @return possible object is {@link NotificationConfiguration }
     * 
     */
    public NotificationConfiguration getNotificationConfiguration() {
	return notificationConfiguration;
    }

    /**
     * Sets the value of the notificationConfiguration property.
     * 
     * @param value
     *            allowed object is {@link NotificationConfiguration }
     * 
     */
    public void setNotificationConfiguration(NotificationConfiguration value) {
	this.notificationConfiguration = value;
    }

}
