//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.22 at 04:47:37 PM EDT 
//

package com.gtnexus.appxpress.platform.module.model.platformmodule;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}globalObjectType"/>
 *         &lt;element ref="{}directoryName"/>
 *         &lt;element ref="{}uiType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "globalObjectType", "directoryName", "uiType" })
@XmlRootElement(name = "customUiConfiguration")
public class CustomUiConfiguration {

    @XmlElement(required = true)
    protected String globalObjectType;
    @XmlElement(required = true)
    protected String directoryName;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String uiType;

    /**
     * Gets the value of the globalObjectType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getGlobalObjectType() {
	return globalObjectType;
    }

    /**
     * Sets the value of the globalObjectType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setGlobalObjectType(String value) {
	this.globalObjectType = value;
    }

    /**
     * Gets the value of the directoryName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDirectoryName() {
	return directoryName;
    }

    /**
     * Sets the value of the directoryName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDirectoryName(String value) {
	this.directoryName = value;
    }

    /**
     * Gets the value of the uiType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUiType() {
	return uiType;
    }

    /**
     * Sets the value of the uiType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUiType(String value) {
	this.uiType = value;
    }

}
