//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.22 at 04:47:37 PM EDT 
//

package com.gtnexus.appxpress.platform.module.model.platformmodule;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}targetType"/>
 *         &lt;element ref="{}apiVersion"/>
 *         &lt;element ref="{}notificationDeliveryMethod"/>
 *         &lt;element ref="{}suppressible"/>
 *         &lt;element ref="{}role"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "targetType", "apiVersion", "notificationDeliveryMethod", "suppressible", "role" })
@XmlRootElement(name = "notificationConfiguration")
public class NotificationConfiguration {

    @XmlElement(required = true)
    protected String targetType;
    @XmlElement(required = true)
    protected BigInteger apiVersion;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String notificationDeliveryMethod;
    protected boolean suppressible;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String role;

    /**
     * Gets the value of the targetType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTargetType() {
	return targetType;
    }

    /**
     * Sets the value of the targetType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTargetType(String value) {
	this.targetType = value;
    }

    /**
     * Gets the value of the apiVersion property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getApiVersion() {
	return apiVersion;
    }

    /**
     * Sets the value of the apiVersion property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setApiVersion(BigInteger value) {
	this.apiVersion = value;
    }

    /**
     * Gets the value of the notificationDeliveryMethod property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNotificationDeliveryMethod() {
	return notificationDeliveryMethod;
    }

    /**
     * Sets the value of the notificationDeliveryMethod property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setNotificationDeliveryMethod(String value) {
	this.notificationDeliveryMethod = value;
    }

    /**
     * Gets the value of the suppressible property.
     * 
     */
    public boolean isSuppressible() {
	return suppressible;
    }

    /**
     * Sets the value of the suppressible property.
     * 
     */
    public void setSuppressible(boolean value) {
	this.suppressible = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRole() {
	return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRole(String value) {
	this.role = value;
    }

}
