//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.21 at 02:11:26 PM EDT 
//

package com.gtnexus.pmm.app.platform.module.model.design;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}code"/>
 *         &lt;element ref="{}roles"/>
 *         &lt;element ref="{}fieldPosition"/>
 *         &lt;element ref="{}objectQueryEnabled"/>
 *         &lt;element ref="{}mutateSelfEnabled"/>
 *         &lt;element ref="{}mutateOthersEnabled"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "code", "roles", "fieldPosition", "objectQueryEnabled", "mutateSelfEnabled",
	"mutateOthersEnabled" })
@XmlRootElement(name = "codExtensionPoint")
public class CodExtensionPoint {

    @XmlElement(required = true)
    protected String code;
    @XmlElement(required = true)
    protected String roles;
    @XmlElement(required = true)
    protected BigInteger fieldPosition;
    @XmlElement(required = true)
    protected String objectQueryEnabled;
    @XmlElement(required = true)
    protected String mutateSelfEnabled;
    @XmlElement(required = true)
    protected String mutateOthersEnabled;

    /**
     * Gets the value of the code property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCode() {
	return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCode(String value) {
	this.code = value;
    }

    /**
     * Gets the value of the roles property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRoles() {
	return roles;
    }

    /**
     * Sets the value of the roles property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRoles(String value) {
	this.roles = value;
    }

    /**
     * Gets the value of the fieldPosition property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getFieldPosition() {
	return fieldPosition;
    }

    /**
     * Sets the value of the fieldPosition property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setFieldPosition(BigInteger value) {
	this.fieldPosition = value;
    }

    /**
     * Gets the value of the objectQueryEnabled property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getObjectQueryEnabled() {
	return objectQueryEnabled;
    }

    /**
     * Sets the value of the objectQueryEnabled property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setObjectQueryEnabled(String value) {
	this.objectQueryEnabled = value;
    }

    /**
     * Gets the value of the mutateSelfEnabled property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMutateSelfEnabled() {
	return mutateSelfEnabled;
    }

    /**
     * Sets the value of the mutateSelfEnabled property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setMutateSelfEnabled(String value) {
	this.mutateSelfEnabled = value;
    }

    /**
     * Gets the value of the mutateOthersEnabled property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMutateOthersEnabled() {
	return mutateOthersEnabled;
    }

    /**
     * Sets the value of the mutateOthersEnabled property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setMutateOthersEnabled(String value) {
	this.mutateOthersEnabled = value;
    }

}
